# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/thomi/Documents/Master/Compilers/giti/Go_compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/thomi/Documents/Master/Compilers/giti/Go_compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/thomi/Documents/Master/Compilers/giti/Go_compiler/CMakeFiles /mnt/c/Users/thomi/Documents/Master/Compilers/giti/Go_compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/thomi/Documents/Master/Compilers/giti/Go_compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gocompiler

# Build rule for target.
Gocompiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Gocompiler
.PHONY : Gocompiler

# fast build rule for target.
Gocompiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/build
.PHONY : Gocompiler/fast

src/ASB/asb.o: src/ASB/asb.cpp.o
.PHONY : src/ASB/asb.o

# target to build an object file
src/ASB/asb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/asb.cpp.o
.PHONY : src/ASB/asb.cpp.o

src/ASB/asb.i: src/ASB/asb.cpp.i
.PHONY : src/ASB/asb.i

# target to preprocess a source file
src/ASB/asb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/asb.cpp.i
.PHONY : src/ASB/asb.cpp.i

src/ASB/asb.s: src/ASB/asb.cpp.s
.PHONY : src/ASB/asb.s

# target to generate assembly for a file
src/ASB/asb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/asb.cpp.s
.PHONY : src/ASB/asb.cpp.s

src/ASB/declaration.o: src/ASB/declaration.cpp.o
.PHONY : src/ASB/declaration.o

# target to build an object file
src/ASB/declaration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/declaration.cpp.o
.PHONY : src/ASB/declaration.cpp.o

src/ASB/declaration.i: src/ASB/declaration.cpp.i
.PHONY : src/ASB/declaration.i

# target to preprocess a source file
src/ASB/declaration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/declaration.cpp.i
.PHONY : src/ASB/declaration.cpp.i

src/ASB/declaration.s: src/ASB/declaration.cpp.s
.PHONY : src/ASB/declaration.s

# target to generate assembly for a file
src/ASB/declaration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/declaration.cpp.s
.PHONY : src/ASB/declaration.cpp.s

src/ASB/expression.o: src/ASB/expression.cpp.o
.PHONY : src/ASB/expression.o

# target to build an object file
src/ASB/expression.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/expression.cpp.o
.PHONY : src/ASB/expression.cpp.o

src/ASB/expression.i: src/ASB/expression.cpp.i
.PHONY : src/ASB/expression.i

# target to preprocess a source file
src/ASB/expression.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/expression.cpp.i
.PHONY : src/ASB/expression.cpp.i

src/ASB/expression.s: src/ASB/expression.cpp.s
.PHONY : src/ASB/expression.s

# target to generate assembly for a file
src/ASB/expression.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/expression.cpp.s
.PHONY : src/ASB/expression.cpp.s

src/ASB/statment.o: src/ASB/statment.cpp.o
.PHONY : src/ASB/statment.o

# target to build an object file
src/ASB/statment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/statment.cpp.o
.PHONY : src/ASB/statment.cpp.o

src/ASB/statment.i: src/ASB/statment.cpp.i
.PHONY : src/ASB/statment.i

# target to preprocess a source file
src/ASB/statment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/statment.cpp.i
.PHONY : src/ASB/statment.cpp.i

src/ASB/statment.s: src/ASB/statment.cpp.s
.PHONY : src/ASB/statment.s

# target to generate assembly for a file
src/ASB/statment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/statment.cpp.s
.PHONY : src/ASB/statment.cpp.s

src/ASB/types.o: src/ASB/types.cpp.o
.PHONY : src/ASB/types.o

# target to build an object file
src/ASB/types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/types.cpp.o
.PHONY : src/ASB/types.cpp.o

src/ASB/types.i: src/ASB/types.cpp.i
.PHONY : src/ASB/types.i

# target to preprocess a source file
src/ASB/types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/types.cpp.i
.PHONY : src/ASB/types.cpp.i

src/ASB/types.s: src/ASB/types.cpp.s
.PHONY : src/ASB/types.s

# target to generate assembly for a file
src/ASB/types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/ASB/types.cpp.s
.PHONY : src/ASB/types.cpp.s

src/Interpreting/interpreting.o: src/Interpreting/interpreting.cpp.o
.PHONY : src/Interpreting/interpreting.o

# target to build an object file
src/Interpreting/interpreting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Interpreting/interpreting.cpp.o
.PHONY : src/Interpreting/interpreting.cpp.o

src/Interpreting/interpreting.i: src/Interpreting/interpreting.cpp.i
.PHONY : src/Interpreting/interpreting.i

# target to preprocess a source file
src/Interpreting/interpreting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Interpreting/interpreting.cpp.i
.PHONY : src/Interpreting/interpreting.cpp.i

src/Interpreting/interpreting.s: src/Interpreting/interpreting.cpp.s
.PHONY : src/Interpreting/interpreting.s

# target to generate assembly for a file
src/Interpreting/interpreting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Interpreting/interpreting.cpp.s
.PHONY : src/Interpreting/interpreting.cpp.s

src/Interpreting/valuedescriptor.o: src/Interpreting/valuedescriptor.cpp.o
.PHONY : src/Interpreting/valuedescriptor.o

# target to build an object file
src/Interpreting/valuedescriptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Interpreting/valuedescriptor.cpp.o
.PHONY : src/Interpreting/valuedescriptor.cpp.o

src/Interpreting/valuedescriptor.i: src/Interpreting/valuedescriptor.cpp.i
.PHONY : src/Interpreting/valuedescriptor.i

# target to preprocess a source file
src/Interpreting/valuedescriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Interpreting/valuedescriptor.cpp.i
.PHONY : src/Interpreting/valuedescriptor.cpp.i

src/Interpreting/valuedescriptor.s: src/Interpreting/valuedescriptor.cpp.s
.PHONY : src/Interpreting/valuedescriptor.s

# target to generate assembly for a file
src/Interpreting/valuedescriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Interpreting/valuedescriptor.cpp.s
.PHONY : src/Interpreting/valuedescriptor.cpp.s

src/Lexer/lexer.o: src/Lexer/lexer.cpp.o
.PHONY : src/Lexer/lexer.o

# target to build an object file
src/Lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Lexer/lexer.cpp.o
.PHONY : src/Lexer/lexer.cpp.o

src/Lexer/lexer.i: src/Lexer/lexer.cpp.i
.PHONY : src/Lexer/lexer.i

# target to preprocess a source file
src/Lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Lexer/lexer.cpp.i
.PHONY : src/Lexer/lexer.cpp.i

src/Lexer/lexer.s: src/Lexer/lexer.cpp.s
.PHONY : src/Lexer/lexer.s

# target to generate assembly for a file
src/Lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Lexer/lexer.cpp.s
.PHONY : src/Lexer/lexer.cpp.s

src/Parser/parser.o: src/Parser/parser.cpp.o
.PHONY : src/Parser/parser.o

# target to build an object file
src/Parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Parser/parser.cpp.o
.PHONY : src/Parser/parser.cpp.o

src/Parser/parser.i: src/Parser/parser.cpp.i
.PHONY : src/Parser/parser.i

# target to preprocess a source file
src/Parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Parser/parser.cpp.i
.PHONY : src/Parser/parser.cpp.i

src/Parser/parser.s: src/Parser/parser.cpp.s
.PHONY : src/Parser/parser.s

# target to generate assembly for a file
src/Parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Parser/parser.cpp.s
.PHONY : src/Parser/parser.cpp.s

src/Visitor/typechecker.o: src/Visitor/typechecker.cpp.o
.PHONY : src/Visitor/typechecker.o

# target to build an object file
src/Visitor/typechecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Visitor/typechecker.cpp.o
.PHONY : src/Visitor/typechecker.cpp.o

src/Visitor/typechecker.i: src/Visitor/typechecker.cpp.i
.PHONY : src/Visitor/typechecker.i

# target to preprocess a source file
src/Visitor/typechecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Visitor/typechecker.cpp.i
.PHONY : src/Visitor/typechecker.cpp.i

src/Visitor/typechecker.s: src/Visitor/typechecker.cpp.s
.PHONY : src/Visitor/typechecker.s

# target to generate assembly for a file
src/Visitor/typechecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Visitor/typechecker.cpp.s
.PHONY : src/Visitor/typechecker.cpp.s

src/Visitor/typedescriptor.o: src/Visitor/typedescriptor.cpp.o
.PHONY : src/Visitor/typedescriptor.o

# target to build an object file
src/Visitor/typedescriptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Visitor/typedescriptor.cpp.o
.PHONY : src/Visitor/typedescriptor.cpp.o

src/Visitor/typedescriptor.i: src/Visitor/typedescriptor.cpp.i
.PHONY : src/Visitor/typedescriptor.i

# target to preprocess a source file
src/Visitor/typedescriptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Visitor/typedescriptor.cpp.i
.PHONY : src/Visitor/typedescriptor.cpp.i

src/Visitor/typedescriptor.s: src/Visitor/typedescriptor.cpp.s
.PHONY : src/Visitor/typedescriptor.s

# target to generate assembly for a file
src/Visitor/typedescriptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/Visitor/typedescriptor.cpp.s
.PHONY : src/Visitor/typedescriptor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Gocompiler.dir/build.make CMakeFiles/Gocompiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Gocompiler"
	@echo "... src/ASB/asb.o"
	@echo "... src/ASB/asb.i"
	@echo "... src/ASB/asb.s"
	@echo "... src/ASB/declaration.o"
	@echo "... src/ASB/declaration.i"
	@echo "... src/ASB/declaration.s"
	@echo "... src/ASB/expression.o"
	@echo "... src/ASB/expression.i"
	@echo "... src/ASB/expression.s"
	@echo "... src/ASB/statment.o"
	@echo "... src/ASB/statment.i"
	@echo "... src/ASB/statment.s"
	@echo "... src/ASB/types.o"
	@echo "... src/ASB/types.i"
	@echo "... src/ASB/types.s"
	@echo "... src/Interpreting/interpreting.o"
	@echo "... src/Interpreting/interpreting.i"
	@echo "... src/Interpreting/interpreting.s"
	@echo "... src/Interpreting/valuedescriptor.o"
	@echo "... src/Interpreting/valuedescriptor.i"
	@echo "... src/Interpreting/valuedescriptor.s"
	@echo "... src/Lexer/lexer.o"
	@echo "... src/Lexer/lexer.i"
	@echo "... src/Lexer/lexer.s"
	@echo "... src/Parser/parser.o"
	@echo "... src/Parser/parser.i"
	@echo "... src/Parser/parser.s"
	@echo "... src/Visitor/typechecker.o"
	@echo "... src/Visitor/typechecker.i"
	@echo "... src/Visitor/typechecker.s"
	@echo "... src/Visitor/typedescriptor.o"
	@echo "... src/Visitor/typedescriptor.i"
	@echo "... src/Visitor/typedescriptor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

